author: Coocier

keywords: Hexo, Personal Blog

description: Lee Coocie的小站

# 导航栏头部名称
nav_name: LEECOOCIE

# 导航栏座右铭
motto: "才发现我的全部努力，不过完成了普通的生活"

github: "https://github.com/coocier/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

# 开启fancybox
fancybox: false

copyright:
  enable: false
  author: "Lee Coocie"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-03-18"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: 52hAx9SaWFeNDlKqcjEn1d2b-gzGzoHsz # 填写您的appid
  appkey: eXpQcCnnMCD0tXFV4n1VR7aC # 填写您的appkey
  comment: true # 是否开启评论系统
  count: true # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: true
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: false
  id: 

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - 6189a4fef88b5a7b0261e99bb782edf7d1b64957a5af399c2368b029e738252d # 1qazxcvb

share:
  twitter: fasle
  facebook: fasle
  weibo: fasle
  qq: fasle
  wechat: fasle

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 
  "360":
    enable: false
    id: 

reward: 
  -
    src: /images/wechat.png
    alt: "WeChat"
  -
    src: /images/alipay.png
    alt: "AliPay"

nav:
  -
    name: "首页"
    path: "/"
  -
    name: "归档"
    path: "/archives/"
  -
    name: "标签"
    path: "/tags/"
  -
    name: "分类"
    path: "/categories/"
  -
    name: "友链"
    path: "/friends/"
  -
    name: "关于"
    path: "/about/"

footer:
  - 
    title: "博客推荐"
    children:
      - 
        name: "LeeCoocie"
        path: "https://coocier.github.io/"
      - 
        name: "阮一峰的个人网站"
        path: "http://ruanyifeng.com/"
  -
    title: "抓到我"
    children: 
      -
        name: "SegmentFault"
        path: "https://segmentfault.com/u/coocier"
      -
        name: "DIV.IO"
        path: "https://div.io/user/coocier"

footer_contact: "Email: leecoocie@gmail.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: https://godbmw.com/blog-static/images/friends/godbmw.jpeg
    site: https://godbmw.com/
    meta: 主题作者
    show: true